/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

export { ERC20__factory } from './ERC20__factory';
export { IERC1155Errors__factory } from './IERC1155Errors__factory';
export { IERC20__factory } from './IERC20__factory';
export { IERC20Errors__factory } from './IERC20Errors__factory';
export { IERC20Metadata__factory } from './IERC20Metadata__factory';
export { IERC721Errors__factory } from './IERC721Errors__factory';
export { InfoContract__factory } from './InfoContract__factory';
export { MyERC20Coin__factory } from './MyERC20Coin__factory';
