/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

export type { ERC20 } from './ERC20';
export type { IERC1155Errors } from './IERC1155Errors';
export type { IERC20 } from './IERC20';
export type { IERC20Errors } from './IERC20Errors';
export type { IERC20Metadata } from './IERC20Metadata';
export type { IERC721Errors } from './IERC721Errors';
export type { InfoContract } from './InfoContract';
export type { MyERC20Coin } from './MyERC20Coin';
export * as factories from './factories';
export { ERC20__factory } from './factories/ERC20__factory';
export { IERC1155Errors__factory } from './factories/IERC1155Errors__factory';
export { IERC20__factory } from './factories/IERC20__factory';
export { IERC20Errors__factory } from './factories/IERC20Errors__factory';
export { IERC20Metadata__factory } from './factories/IERC20Metadata__factory';
export { IERC721Errors__factory } from './factories/IERC721Errors__factory';
export { InfoContract__factory } from './factories/InfoContract__factory';
export { MyERC20Coin__factory } from './factories/MyERC20Coin__factory';
